import "./check-ui-modeling.mjs";
import "./check-registry.mjs";
import "./check-mention-a11y.mjs";
import "./check-purpose-atlas.mjs";
import "./check-purpose-atlas-fixture-boundaries.mjs";
import "./check-a2ui-shell-data-boundary.mjs";
import "./check-generic-a2ui-shell-builder.mjs";
import "./check-markdown-document-renderer.mjs";
import "./check-markdown-renderer-boundary-regressions.mjs";
import "./check-ci-workflows.mjs";
console.log("ui-all-checks-pass");
